<?php

namespace Database\Seeders;

use App\Models\Category;
use Illuminate\Database\Seeder;

class CategorySeeder extends Seeder
{
    /**
     * Run the database seeds for 20 Topics across 3 Pillars.
     */
    public function run(): void
    {
        $categories = [
            // =========================================================================
            // PILAR 1: ZONA MENGENAL (10 Topik)
            // =========================================================================
            [
                'pillar' => 'mengenal',
                'name' => 'Huruf Abjad Ceria',
                'slug' => 'abjad',
                'icon_emoji' => '🔤',
                'color_theme' => 'emerald',
                'bg_gradient' => 'from-emerald-400 to-teal-500',
                'border_color' => '#10b981',
                'subtitle' => 'Mengenal bunyi huruf & alfabet A sampai Z',
                'description' => 'Materi fonik huruf abjad A sampai Z lengkap dengan contoh kata bergambar dan suara pelafalan.',
                'age_min' => 3,
                'age_max' => 5,
                'recommended_age' => '3 - 5 Thn',
                'sort_order' => 1,
            ],
            [
                'pillar' => 'mengenal',
                'name' => 'Mengenal Angka Cerdas',
                'slug' => 'angka',
                'icon_emoji' => '🔢',
                'color_theme' => 'sky',
                'bg_gradient' => 'from-sky-400 to-blue-500',
                'border_color' => '#0284c7',
                'subtitle' => 'Mengenal lambang bilangan 1 sampai 20',
                'description' => 'Materi pengenalan bentuk angka, sebutan bilangan, dan jumlah kuantitas benda konkret.',
                'age_min' => 3,
                'age_max' => 5,
                'recommended_age' => '3 - 5 Thn',
                'sort_order' => 2,
            ],
            [
                'pillar' => 'mengenal',
                'name' => 'Huruf Hijaiyah Cilik',
                'slug' => 'hijaiyah',
                'icon_emoji' => '🌙',
                'color_theme' => 'purple',
                'bg_gradient' => 'from-purple-400 to-indigo-500',
                'border_color' => '#8b5cf6',
                'subtitle' => 'Mengenal huruf hijaiyah Alif sampai Ya',
                'description' => 'Mengenalkan huruf hijaiyah Alif, Ba, Ta, Tsa dengan lafal makhraj sederhana ramah anak.',
                'age_min' => 3,
                'age_max' => 6,
                'recommended_age' => '3 - 6 Thn',
                'sort_order' => 3,
            ],
            [
                'pillar' => 'mengenal',
                'name' => 'Satwa & Hewan Lucu',
                'slug' => 'hewan',
                'icon_emoji' => '🦁',
                'color_theme' => 'yellow',
                'bg_gradient' => 'from-amber-400 to-yellow-500',
                'border_color' => '#f59e0b',
                'subtitle' => 'Mengenal suara & nama satwa lucu rimba',
                'description' => 'Materi pengenalan ragam satwa darat, air, dan udara lengkap dengan suara tiruan dan pelafalan suku kata.',
                'age_min' => 3,
                'age_max' => 5,
                'recommended_age' => '3 - 5 Thn',
                'sort_order' => 4,
            ],
            [
                'pillar' => 'mengenal',
                'name' => 'Buah & Sayuran Segar',
                'slug' => 'buah',
                'icon_emoji' => '🍎',
                'color_theme' => 'rose',
                'bg_gradient' => 'from-rose-400 to-red-500',
                'border_color' => '#f43f5e',
                'subtitle' => 'Mengenal aneka buah manis dan sayur sehat',
                'description' => 'Eksplorasi warna, rasa, tekstur, dan manfaat vitamin dari berbagai buah-buahan dan sayuran.',
                'age_min' => 3,
                'age_max' => 5,
                'recommended_age' => '3 - 5 Thn',
                'sort_order' => 5,
            ],
            [
                'pillar' => 'mengenal',
                'name' => 'Mengenal Warna Ceria',
                'slug' => 'warna',
                'icon_emoji' => '🎨',
                'color_theme' => 'indigo',
                'bg_gradient' => 'from-indigo-400 to-purple-500',
                'border_color' => '#6366f1',
                'subtitle' => 'Mengenal aneka warna primer, sekunder & gradasi ceria',
                'description' => 'Pengenalan warna primer, sekunder, warna alam, serta sains pencampuran warna yang seru.',
                'age_min' => 3,
                'age_max' => 5,
                'recommended_age' => '3 - 5 Thn',
                'sort_order' => 6,
            ],
            [
                'pillar' => 'mengenal',
                'name' => 'Mengenal Bentuk Geometri Indah',
                'slug' => 'bentuk',
                'icon_emoji' => '🔷',
                'color_theme' => 'cyan',
                'bg_gradient' => 'from-cyan-400 to-blue-500',
                'border_color' => '#06b6d4',
                'subtitle' => 'Mengenal bentuk 2D, 3D & geometri ceria',
                'description' => 'Pengenalan bentuk dasar lingkaran, segitiga, persegi, bintang, hingga bangun ruang kubus, bola, dan tabung.',
                'age_min' => 3,
                'age_max' => 6,
                'recommended_age' => '3 - 6 Thn',
                'sort_order' => 7,
            ],
            [
                'pillar' => 'mengenal',
                'name' => 'Jenis Kendaraan Hebat',
                'slug' => 'kendaraan',
                'icon_emoji' => '🚗',
                'color_theme' => 'sky',
                'bg_gradient' => 'from-cyan-400 to-blue-500',
                'border_color' => '#06b6d4',
                'subtitle' => 'Mengenal kendaraan darat, laut, dan udara',
                'description' => 'Materi transportasi roda dua, roda empat, kereta api cepat, kapal pesiar, dan pesawat terbang.',
                'age_min' => 3,
                'age_max' => 6,
                'recommended_age' => '3 - 6 Thn',
                'sort_order' => 8,
            ],
            [
                'pillar' => 'mengenal',
                'name' => 'Benda di Sekitar Kita',
                'slug' => 'benda',
                'icon_emoji' => '🧸',
                'color_theme' => 'amber',
                'bg_gradient' => 'from-amber-400 to-orange-500',
                'border_color' => '#d97706',
                'subtitle' => 'Mengenal peralatan rumah dan sekolah',
                'description' => 'Mengenal benda sehari-hari seperti meja, kursi, tas sekolah, pensil, sepatu, dan mainan.',
                'age_min' => 3,
                'age_max' => 5,
                'recommended_age' => '3 - 5 Thn',
                'sort_order' => 9,
            ],
            [
                'pillar' => 'mengenal',
                'name' => 'Bendera Negara Dunia',
                'slug' => 'bendera',
                'icon_emoji' => '🚩',
                'color_theme' => 'rose',
                'bg_gradient' => 'from-red-400 to-rose-600',
                'border_color' => '#e11d48',
                'subtitle' => 'Mengenal bendera Indonesia dan sahabat dunia',
                'description' => 'Mengenalkan warna dan lambang bendera negara Indonesia, Palestina, Arab Saudi, Malaysia, Jepang, dll.',
                'age_min' => 4,
                'age_max' => 6,
                'recommended_age' => '4 - 6 Thn',
                'sort_order' => 10,
            ],
            [
                'pillar' => 'mengenal',
                'name' => 'Anggota Tubuh & Panca Indra',
                'slug' => 'tubuh',
                'icon_emoji' => '👀',
                'color_theme' => 'emerald',
                'bg_gradient' => 'from-emerald-400 to-green-600',
                'border_color' => '#059669',
                'subtitle' => 'Mengenal fungsi mata, telinga, tangan, dan kaki',
                'description' => 'Mengenal bagian tubuh ciptaan Tuhan dan merawat kebersihan tubuh dengan rasa syukur.',
                'age_min' => 3,
                'age_max' => 6,
                'recommended_age' => '3 - 6 Thn',
                'sort_order' => 11,
            ],
            [
                'pillar' => 'mengenal',
                'name' => 'Mengenal Alat Musik',
                'slug' => 'alat-musik',
                'icon_emoji' => '🎵',
                'color_theme' => 'purple',
                'bg_gradient' => 'from-purple-400 to-pink-500',
                'border_color' => '#a855f7',
                'subtitle' => 'Mengenal suara & bentuk alat musik merdu',
                'description' => 'Materi pengenalan aneka alat musik petik, tiup, pukul, dan tuts lengkap dengan suara tiruan dan pelafalan suku kata.',
                'age_min' => 3,
                'age_max' => 6,
                'recommended_age' => '3 - 6 Thn',
                'sort_order' => 12,
            ],

            // =========================================================================
            // PILAR 2: ZONA BELAJAR MEMBACA (5 Topik)
            // =========================================================================
            [
                'pillar' => 'membaca',
                'name' => 'Huruf Vokal & Fonik Ceria',
                'slug' => 'huruf-vokal',
                'icon_emoji' => '🅰️',
                'color_theme' => 'sky',
                'bg_gradient' => 'from-sky-400 to-indigo-500',
                'border_color' => '#0284c7',
                'subtitle' => 'Belajar bunyi vokal A - I - U - E - O',
                'description' => 'Mengenal pengucapan huruf vokal dan asosiasi gambar kata benda yang mudah diingat.',
                'age_min' => 4,
                'age_max' => 6,
                'recommended_age' => '4 - 6 Thn',
                'sort_order' => 11,
            ],
            [
                'pillar' => 'membaca',
                'name' => 'Membaca 2 Suku Kata',
                'slug' => 'dua-suku-kata',
                'icon_emoji' => '🗣️',
                'color_theme' => 'emerald',
                'bg_gradient' => 'from-teal-400 to-emerald-600',
                'border_color' => '#0d9488',
                'subtitle' => 'Membaca kata mudah: Bo-la, Bu-ku, Ku-da',
                'description' => 'Latihan mengeja dan membaca kata berpola Konsonan-Vokal Konsonan-Vokal (KV-KV).',
                'age_min' => 4,
                'age_max' => 6,
                'recommended_age' => '4 - 6 Thn',
                'sort_order' => 12,
            ],
            [
                'pillar' => 'membaca',
                'name' => 'Membaca 3 Suku Kata',
                'slug' => 'tiga-suku-kata',
                'icon_emoji' => '📚',
                'color_theme' => 'purple',
                'bg_gradient' => 'from-purple-400 to-fuchsia-600',
                'border_color' => '#9333ea',
                'subtitle' => 'Membaca kata seru: Se-pe-da, Ke-la-pa',
                'description' => 'Tingkat lanjutan membaca kata 3 suku kata terbuka yang sering dijumpai sehari-hari.',
                'age_min' => 5,
                'age_max' => 6,
                'recommended_age' => '5 - 6 Thn',
                'sort_order' => 13,
            ],
            [
                'pillar' => 'membaca',
                'name' => 'Kata Berakhiran Konsonan',
                'slug' => 'akhiran-konsonan',
                'icon_emoji' => '🧩',
                'color_theme' => 'amber',
                'bg_gradient' => 'from-amber-400 to-yellow-600',
                'border_color' => '#d97706',
                'subtitle' => 'Membaca kata berakhiran: Ru-mah, A-yam',
                'description' => 'Mengenal akhiran -m, -h, -n, -ng, dan -r pada kata benda bergambar.',
                'age_min' => 5,
                'age_max' => 6,
                'recommended_age' => '5 - 6 Thn',
                'sort_order' => 14,
            ],
            [
                'pillar' => 'membaca',
                'name' => 'Cerita Pendek Bergambar',
                'slug' => 'cerita-pendek',
                'icon_emoji' => '📖',
                'color_theme' => 'yellow',
                'bg_gradient' => 'from-yellow-400 to-amber-600',
                'border_color' => '#ca8a04',
                'subtitle' => 'Membaca 1-2 kalimat cerita bergambar ceria',
                'description' => 'Membaca kalimat bermakna penuh ilustrasi untuk melatih pemahaman bacaan awal.',
                'age_min' => 5,
                'age_max' => 6,
                'recommended_age' => '5 - 6 Thn',
                'sort_order' => 15,
            ],

            // =========================================================================
            // PILAR 3: ZONA BELAJAR MENGHITUNG (5 Topik)
            // =========================================================================
            [
                'pillar' => 'menghitung',
                'name' => 'Membilang Benda Ceria',
                'slug' => 'membilang',
                'icon_emoji' => '🎈',
                'color_theme' => 'sky',
                'bg_gradient' => 'from-sky-400 to-cyan-500',
                'border_color' => '#0284c7',
                'subtitle' => 'Menghitung jumlah benda 1 sampai 10',
                'description' => 'Menghitung objek visual nyata seperti balon, bintang, bola, dan buah.',
                'age_min' => 3,
                'age_max' => 5,
                'recommended_age' => '3 - 5 Thn',
                'sort_order' => 16,
            ],
            [
                'pillar' => 'menghitung',
                'name' => 'Perbandingan Ukuran & Jumlah',
                'slug' => 'perbandingan',
                'icon_emoji' => '⚖️',
                'color_theme' => 'indigo',
                'bg_gradient' => 'from-indigo-400 to-blue-600',
                'border_color' => '#4f46e5',
                'subtitle' => 'Membedakan banyak-sedikit dan besar-kecil',
                'description' => 'Membandingkan kelompok benda yang lebih banyak, lebih sedikit, lebih besar, atau lebih tinggi.',
                'age_min' => 4,
                'age_max' => 6,
                'recommended_age' => '4 - 6 Thn',
                'sort_order' => 17,
            ],
            [
                'pillar' => 'menghitung',
                'name' => 'Penjumlahan Bergambar',
                'slug' => 'penjumlahan',
                'icon_emoji' => '➕',
                'color_theme' => 'emerald',
                'bg_gradient' => 'from-emerald-400 to-teal-600',
                'border_color' => '#059669',
                'subtitle' => 'Belajar tambah-tambahan buah & balon',
                'description' => 'Konsep penggabungan dua kelompok benda konkret dengan hasil maksimal 10.',
                'age_min' => 4,
                'age_max' => 6,
                'recommended_age' => '4 - 6 Thn',
                'sort_order' => 18,
            ],
            [
                'pillar' => 'menghitung',
                'name' => 'Pengurangan Bergambar',
                'slug' => 'pengurangan',
                'icon_emoji' => '➖',
                'color_theme' => 'rose',
                'bg_gradient' => 'from-rose-400 to-red-600',
                'border_color' => '#e11d48',
                'subtitle' => 'Belajar kurang-kurangan benda lucu',
                'description' => 'Konsep memisahkan atau mengambil sebagian benda dari kelompok dengan ilustrasi visual.',
                'age_min' => 5,
                'age_max' => 6,
                'recommended_age' => '5 - 6 Thn',
                'sort_order' => 19,
            ],
            [
                'pillar' => 'menghitung',
                'name' => 'Pola Urutan & Logika',
                'slug' => 'pola-logika',
                'icon_emoji' => '🧩',
                'color_theme' => 'purple',
                'bg_gradient' => 'from-purple-400 to-indigo-600',
                'border_color' => '#7c3aed',
                'subtitle' => 'Menyusun urutan warna & bentuk cerdas',
                'description' => 'Menebak pola keberulangan (AB-AB atau ABC-ABC) untuk melatih logika berpikir komputasional anak.',
                'age_min' => 4,
                'age_max' => 6,
                'recommended_age' => '4 - 6 Thn',
                'sort_order' => 20,
            ],
        ];

        foreach ($categories as $cat) {
            Category::updateOrCreate(['slug' => $cat['slug']], $cat);
        }
    }
}
